add OpenAPI specification
KruASe76/news-recommendation-service pull request #24
Opened 2024-10-27 17:21 UTC by KruASe76

resolves #4

посмотреть срендеренную доку можно [тут](https://editor.swagger.io), скопипастив содержимое файлика из изменений
(я не знаю, почему он ругается на версию 3.1.0, ведь она [уже 3 года как последняя](https://en.wikipedia.org/wiki/OpenAPI_Specification))

2024-10-27 19:43 UTC, AlexanderBobryakov requested changes

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +    description: Operations with news sources
Мелочь - `source` очень общее слово, лучше бы уточнить.

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          example: "Artificial Intelligence"
Кажется не хватает даты статьи и ее содержимого.

Идентификатор вызывает сомнения, но пусть останется. Потому что эти статьи можно было бы не хранить в бд и запрашивать их по запросу клиента сразу из интернета. Но посмотрим дальше на вашу реализацию

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          description: No new articles found
208 не соответствует описанию, кажется он тут вообще не нужен. Если статей нет, то будет отправлен пустой список со статусом 200.

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          description: Invalid or expired access token
о каком access токене идет речь? Давайте тут не усложнять и сделаем обычную basic-авторизацию

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          description: Validation error
О какой валидации речь? Клиент в этом ендпоинте не передает никаких параметров требующих валидацию

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
Слово `custom` лишнее

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +      summary: Create custom topic
А что значит "создает"? Предполагается что создание идет к конкретному юзеру? Если нет, то может быть такое,  что разные клиенты могут видеть кучу лишних топиков других клиентов через get всех /topics

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /topics:
Ендпоинт на удаление топика нужен?

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          description: Too many topics
А у нас есть ограничение количества топиков для человека?

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /sources:
По /source и другим ендпоинтам аналогичные вопросы

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /user/auth/check:
Вот эти все ендпоинты для работы с токенами не нужны, остановимся на basic

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +              $ref: '#/components/schemas/IdList'
`IdList` слишком общее название. Лучше конкретизировать. Если схема используется также в других местах, то лучше эти схемы разделить на несколько.

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +                $ref: '#/components/schemas/HttpTooMany'
Интересно каким образом эта часть документации будет реализована

2024-10-27 19:43 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          example: "Email already exists"
Не обязательно, но под ошибки и проблемы можно воспользоваться универсальной схемой ответа - ProblemDetails (можно погуглить)

2024-10-27 20:06 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +    description: Operations with news sources
окей

2024-10-27 20:07 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          example: "Artificial Intelligence"
а мы разве будем всю статью пользователю в тг выплевывать?
мне казалось, что логичнее давать ссылку и все...
про дату согласен

2024-10-27 20:07 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          description: No new articles found
ладно, ладно, заоверинженерил)

2024-10-27 20:09 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          description: Invalid or expired access token
то есть надо будет при каждом запросе в заголовок пихать "почта:пароль" в base64? ыыыххх..

2024-10-27 20:09 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          description: Validation error
ой, правда, там лишнее

2024-10-27 20:11 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +      summary: Create custom topic
да, кастомный топики привязаны к юзерам, которые их создали
поэтому get топиков без auth возвращает только дефолтные, а с auth - дефольные + кастомные

2024-10-27 20:12 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
я как раз хотел бы разграничить операции над всеми топиками и конкретно над кастомными

2024-10-27 20:12 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +  /topics:
ну, в целом, можно

2024-10-27 20:12 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          description: Too many topics
в тз было вроде

2024-10-27 20:19 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +  /user/auth/check:
![](https://media1.tenor.com/m/LMkaU9AKygAAAAAC/fbt-renvor.gif)

2024-10-27 20:24 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +  /sources:
...и аналогичные ответы)

2024-10-27 20:24 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +              $ref: '#/components/schemas/IdList'
ну это просто список интов, который я просто вынес под отдельным названием
тогда уж проще написать прямо тут, что это список интов, но я стараюсь избегать описания схем прямо в эндпоинтах

2024-10-27 20:24 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +                $ref: '#/components/schemas/HttpTooMany'
в тз были лимиты на количество топиков/сайтов на юзера

2024-10-27 20:24 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          example: "Email already exists"
ну в целом да, но тут всего один такой тип, и я решил, что так будет проще

2024-10-28 08:38 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          example: "Artificial Intelligence"
> а мы разве будем всю статью пользователю в тг выплевывать?

Ну как сделаете. Можно получать все описание и обрезать до первых 1000 символов. Можно просто ссылку отдавать. 

Давайте просто ссылку, посмотрим как получится

2024-10-28 08:39 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          description: Invalid or expired access token
Думаю реализовывать полноценную аутентификацию будет больнее... Я бы сейчас не накручивал в проект сложностей. Можно было бы уже потом поправить как улучшение готовой части

2024-10-28 08:40 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +              $ref: '#/components/schemas/IdList'
Ну окей, я тут не навязываю

2024-10-28 08:49 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
А окей, тогда тут статус не подходит. 413 - это про то, что размер payload в запросе слишком большой.  На серверах выставляют ограничения на размер входного запроса. Тут можно либо никакой статус не указывать (потом разберемся с ним), либо найти более подходящий, типа 409  и тп

2024-10-28 08:49 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +      summary: Create custom topic
Ок, давайте в этом направлении двигаться

2024-10-28 08:50 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +                $ref: '#/components/schemas/HttpTooMany'
А окей, тогда тут статус не подходит. 413 - это про то, что размер payload в запросе слишком большой. На серверах выставляют ограничения на размер входного запроса. Тут можно либо никакой статус не указывать (потом разберемся с ним), либо найти более подходящий, типа 409 и тп

2024-10-28 08:51 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          example: "Email already exists"
окей

2024-10-28 08:52 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
Так это аналогичный ресурс: и то и то - топики. У человека есть список топиков и кажется ему не важно какие из них кастомные, а какие нет. То есть есть два ендпоинта: добавить топик мне и удалить мой топик

2024-10-28 08:53 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +          description: Too many topics
Окей, тогда 413 статус не подходит

2024-10-28 10:23 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          description: Invalid or expired access token
ну ладно(

2024-10-28 10:26 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
но чтобы добавить дефолтный топик, нужно всего лишь тыкнуть на вариант, а чтобы добавить кастомный, его надо текстом вводить и вот это все

2024-10-28 10:27 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
так что именно добавлять кастомные топики - один эндпоинт, а выбирать, на какие подписаться - другой

2024-10-28 10:32 UTC, KruASe76 commented on app/src/main/resources/openapi.yml
> +          description: Too many topics
тогда 406?

2024-10-28 17:10 UTC, AlexanderBobryakov commented on app/src/main/resources/openapi.yml
> +  /topics/custom:
> но чтобы добавить дефолтный топик, нужно всего лишь тыкнуть на вариант, а чтобы добавить кастомный, его надо текстом вводить и вот это все

Но в запросе полетит одинаковая информация? Сейчас ты говоришь с точки зрения реализации фронтенд-части. Я могу такой же аргумент привести:
- если отправляет дефолтный, то в запросе летит POST с названием топика
- если отправляет не дефолтный, то в запросе летит POST с названием кастомного топика

В общем тут можно и так и так реализовать. Предлагаю на этом не засиживаться - принимаю твой вариант, посмотрим как дальше по реализации пойдет, если что - подправим

2024-10-28 17:11 UTC, AlexanderBobryakov approved these changes

2024-10-28 17:24 UTC, merged